ajout ZAP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,7 +11,8 @@ jobs:
   api-tests:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name : Checkout code
+        uses: actions/checkout@v4
 
       - name: Set up JDK 11
         uses: actions/setup-java@v4
@@ -22,7 +23,6 @@ jobs:
       - name: generate an start API
         run: | 
           mvn -q clean package
-          find . -name *.jar
           nohup java -jar ./target/formation-cicd-test-tp-03-1.0-SNAPSHOT.jar > app.log 2>&1 &
 
       - name: Wait for API to be ready
@@ -60,5 +60,52 @@ jobs:
         with:
           name: api-test-reports
           path: api-test-reports/
+
+  security-scan:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v4
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven
+      - name: generate an start API
+        run: |
+          mvn -q clean package
+          nohup java -jar ./target/formation-cicd-test-tp-03-1.0-SNAPSHOT.jar > app.log 2>&1 &
+
+      - name: Wait for API to be ready
+        run: |
+          for i in {1..30}; do
+            if curl -sSf http://localhost:8080/health > /dev/null; then
+              echo "API is up!"
+              exit 0
+            fi
+            echo "Waiting API..."
+            sleep 2
+          done
+          echo "API not ready"
+          if [ -f app.log ]; then
+          tail -n 200 app.log
+          else
+          echo "Log file app.log not found."
+          fi
+          exit 1
+      - name: Base OWASP ZAP Scan
+        uses: zaproxy/action-baseline@v0.15.0
+        with:
+          target: 'http://host.docker.internal:8080'
+
+      - name: Upload ZAP report
+        if: always()
+        uses: actions/upload-artifact@v5
+        with:
+          name: zap-report
+          path: report.html
 
 
